services:
  postgres:
    image: postgres:17-alpine
    container_name: ennas-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ennas_lennas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ennas_lennas_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-28Z
    container_name: ennas-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: n62JqnPRXJRV2JAHDCg8
      MINIO_ROOT_PASSWORD: XgySJpBcz2wU6NSlF3cvpXK87CUDFj4Q6ZOcrysy
    ports:
      - "9008:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ennas-backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ennas_lennas_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      MINIO_URL: http://minio:9000
      MINIO_KEY: n62JqnPRXJRV2JAHDCg8
      MINIO_SECRET: XgySJpBcz2wU6NSlF3cvpXK87CUDFj4Q6ZOcrysy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ennas-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data:
  minio_data:
